FROM tensorflow/tensorflow:1.8.0-gpu-py3

RUN apt-get update && apt-get install -y --no-install-recommends git

RUN pip uninstall -y jupyter ipykernel                               \
 && rm -rf /notebooks                                                \ 
 && rm -f /run_jupyter.sh                                            \
 && rm -f /root/.jupyter/jupyter_notebook_config.py                  \
 && rm -f /tensorflow_gpu-1.8.0-cp35-cp35m-manylinux1_x86_64.whl

ADD requeriments.txt /tmp/
RUN cd /tmp && pip install --user -r requeriments.txt

RUN cd /tmp                                                          \
 && git clone https://github.com/felippe-mendonca/tf-pose-estimation \
 && cd tf-pose-estimation                                            \
 && bash bootstrap.sh                                                \
 && pip install --user .

ADD models/ /models/
RUN rm -rf /tmp/*