# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: skeletons.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='skeletons.proto',
  package='is.vision',
  syntax='proto3',
  serialized_pb=_b('\n\x0fskeletons.proto\x12\tis.vision\"i\n\x0cSkeletonPart\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.is.vision.SkeletonPartType\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x05 \x01(\x02\x12\r\n\x05score\x18\x04 \x01(\x02\"d\n\x0cSkeletonLink\x12*\n\x05\x62\x65gin\x18\x01 \x01(\x0e\x32\x1b.is.vision.SkeletonPartType\x12(\n\x03\x65nd\x18\x02 \x01(\x0e\x32\x1b.is.vision.SkeletonPartType\"2\n\x08Skeleton\x12&\n\x05parts\x18\x01 \x03(\x0b\x32\x17.is.vision.SkeletonPart\"\x84\x01\n\tSkeletons\x12&\n\tskeletons\x18\x01 \x03(\x0b\x32\x13.is.vision.Skeleton\x12&\n\x05links\x18\x02 \x03(\x0b\x32\x17.is.vision.SkeletonLink\x12\'\n\x05model\x18\x03 \x01(\x0e\x32\x18.is.vision.SkeletonModel*#\n\rSkeletonModel\x12\x08\n\x04\x43OCO\x10\x00\x12\x08\n\x04MPII\x10\x01*\xd8\x02\n\x10SkeletonPartType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04HEAD\x10\x01\x12\x08\n\x04NOSE\x10\x02\x12\x08\n\x04NECK\x10\x03\x12\x12\n\x0eRIGHT_SHOULDER\x10\x04\x12\x0f\n\x0bRIGHT_ELBOW\x10\x05\x12\x0f\n\x0bRIGHT_WRIST\x10\x06\x12\x11\n\rLEFT_SHOULDER\x10\x07\x12\x0e\n\nLEFT_ELBOW\x10\x08\x12\x0e\n\nLEFT_WRIST\x10\t\x12\r\n\tRIGHT_HIP\x10\n\x12\x0e\n\nRIGHT_KNEE\x10\x0b\x12\x0f\n\x0bRIGHT_ANKLE\x10\x0c\x12\x0c\n\x08LEFT_HIP\x10\r\x12\r\n\tLEFT_KNEE\x10\x0e\x12\x0e\n\nLEFT_ANKLE\x10\x0f\x12\r\n\tRIGHT_EYE\x10\x10\x12\x0c\n\x08LEFT_EYE\x10\x11\x12\r\n\tRIGHT_EAR\x10\x12\x12\x0c\n\x08LEFT_EAR\x10\x13\x12\t\n\x05\x43HEST\x10\x14\x12\x0e\n\nBACKGROUND\x10\x15\x42\x11\n\rcom.is.visionP\x01\x62\x06proto3')
)

_SKELETONMODEL = _descriptor.EnumDescriptor(
  name='SkeletonModel',
  full_name='is.vision.SkeletonModel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COCO', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MPII', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=426,
  serialized_end=461,
)
_sym_db.RegisterEnumDescriptor(_SKELETONMODEL)

SkeletonModel = enum_type_wrapper.EnumTypeWrapper(_SKELETONMODEL)
_SKELETONPARTTYPE = _descriptor.EnumDescriptor(
  name='SkeletonPartType',
  full_name='is.vision.SkeletonPartType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEAD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOSE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NECK', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_SHOULDER', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_ELBOW', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_WRIST', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_SHOULDER', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_ELBOW', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_WRIST', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_HIP', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_KNEE', index=11, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_ANKLE', index=12, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_HIP', index=13, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_KNEE', index=14, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_ANKLE', index=15, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_EYE', index=16, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_EYE', index=17, number=17,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_EAR', index=18, number=18,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_EAR', index=19, number=19,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHEST', index=20, number=20,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BACKGROUND', index=21, number=21,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=464,
  serialized_end=808,
)
_sym_db.RegisterEnumDescriptor(_SKELETONPARTTYPE)

SkeletonPartType = enum_type_wrapper.EnumTypeWrapper(_SKELETONPARTTYPE)
COCO = 0
MPII = 1
UNKNOWN = 0
HEAD = 1
NOSE = 2
NECK = 3
RIGHT_SHOULDER = 4
RIGHT_ELBOW = 5
RIGHT_WRIST = 6
LEFT_SHOULDER = 7
LEFT_ELBOW = 8
LEFT_WRIST = 9
RIGHT_HIP = 10
RIGHT_KNEE = 11
RIGHT_ANKLE = 12
LEFT_HIP = 13
LEFT_KNEE = 14
LEFT_ANKLE = 15
RIGHT_EYE = 16
LEFT_EYE = 17
RIGHT_EAR = 18
LEFT_EAR = 19
CHEST = 20
BACKGROUND = 21



_SKELETONPART = _descriptor.Descriptor(
  name='SkeletonPart',
  full_name='is.vision.SkeletonPart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='is.vision.SkeletonPart.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='is.vision.SkeletonPart.x', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='is.vision.SkeletonPart.y', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='is.vision.SkeletonPart.z', index=3,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='is.vision.SkeletonPart.score', index=4,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=135,
)


_SKELETONLINK = _descriptor.Descriptor(
  name='SkeletonLink',
  full_name='is.vision.SkeletonLink',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='begin', full_name='is.vision.SkeletonLink.begin', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='is.vision.SkeletonLink.end', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=237,
)


_SKELETON = _descriptor.Descriptor(
  name='Skeleton',
  full_name='is.vision.Skeleton',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parts', full_name='is.vision.Skeleton.parts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=289,
)


_SKELETONS = _descriptor.Descriptor(
  name='Skeletons',
  full_name='is.vision.Skeletons',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='skeletons', full_name='is.vision.Skeletons.skeletons', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='links', full_name='is.vision.Skeletons.links', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='is.vision.Skeletons.model', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=424,
)

_SKELETONPART.fields_by_name['type'].enum_type = _SKELETONPARTTYPE
_SKELETONLINK.fields_by_name['begin'].enum_type = _SKELETONPARTTYPE
_SKELETONLINK.fields_by_name['end'].enum_type = _SKELETONPARTTYPE
_SKELETON.fields_by_name['parts'].message_type = _SKELETONPART
_SKELETONS.fields_by_name['skeletons'].message_type = _SKELETON
_SKELETONS.fields_by_name['links'].message_type = _SKELETONLINK
_SKELETONS.fields_by_name['model'].enum_type = _SKELETONMODEL
DESCRIPTOR.message_types_by_name['SkeletonPart'] = _SKELETONPART
DESCRIPTOR.message_types_by_name['SkeletonLink'] = _SKELETONLINK
DESCRIPTOR.message_types_by_name['Skeleton'] = _SKELETON
DESCRIPTOR.message_types_by_name['Skeletons'] = _SKELETONS
DESCRIPTOR.enum_types_by_name['SkeletonModel'] = _SKELETONMODEL
DESCRIPTOR.enum_types_by_name['SkeletonPartType'] = _SKELETONPARTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SkeletonPart = _reflection.GeneratedProtocolMessageType('SkeletonPart', (_message.Message,), dict(
  DESCRIPTOR = _SKELETONPART,
  __module__ = 'skeletons_pb2'
  # @@protoc_insertion_point(class_scope:is.vision.SkeletonPart)
  ))
_sym_db.RegisterMessage(SkeletonPart)

SkeletonLink = _reflection.GeneratedProtocolMessageType('SkeletonLink', (_message.Message,), dict(
  DESCRIPTOR = _SKELETONLINK,
  __module__ = 'skeletons_pb2'
  # @@protoc_insertion_point(class_scope:is.vision.SkeletonLink)
  ))
_sym_db.RegisterMessage(SkeletonLink)

Skeleton = _reflection.GeneratedProtocolMessageType('Skeleton', (_message.Message,), dict(
  DESCRIPTOR = _SKELETON,
  __module__ = 'skeletons_pb2'
  # @@protoc_insertion_point(class_scope:is.vision.Skeleton)
  ))
_sym_db.RegisterMessage(Skeleton)

Skeletons = _reflection.GeneratedProtocolMessageType('Skeletons', (_message.Message,), dict(
  DESCRIPTOR = _SKELETONS,
  __module__ = 'skeletons_pb2'
  # @@protoc_insertion_point(class_scope:is.vision.Skeletons)
  ))
_sym_db.RegisterMessage(Skeletons)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\rcom.is.visionP\001'))
# @@protoc_insertion_point(module_scope)
