FROM tensorflow/tensorflow:1.11.0-gpu-py3

RUN pip uninstall -y jupyter ipykernel                               \
 && rm -rf /notebooks                                                \ 
 && rm -f /run_jupyter.sh                                            \
 && rm -f /root/.jupyter/jupyter_notebook_config.py                  \
 && rm -f /tensorflow_gpu-1.11.0-cp35-cp35m-manylinux1_x86_64.whl

RUN apt-get update && apt-get install -y --no-install-recommends \
    git wget libsm6 libxext6 libxrender-dev 

ADD requeriments.txt /tmp/
RUN cd /tmp && pip install --user -r requeriments.txt

RUN cd /tmp                                                  \
 && git clone https://github.com/ildoonet/tf-pose-estimation \
 && cd tf-pose-estimation                                    \
 && git checkout b119759e8a41828c633bd39b5c883bf5a56a214f    \
 && cd models/graph/cmu/ && bash download.sh && cd ../../../ \
 && pip install --user .

RUN rm -rf /tmp/*