FROM nvidia/cuda:8.0-cudnn5-devel

WORKDIR /tmp/
ADD bootstrap.sh .
RUN bash bootstrap.sh

RUN apt purge -y python3-pip python-pip \
    && curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
    && python3 get-pip.py \
    && pip install conan_package_tools
ENV CONAN_USERNAME is
ENV CONAN_LOGIN_USERNAME is
ENV CONAN_CHANNEL stable

# build caffe and openpose packages
ADD etc/packages/ /tmp/packages/
WORKDIR /tmp/packages
RUN cd caffe/           \
    && python3 build.py \
    && cd ../openpose/  \
    && python3 build.py

# genereal dependencies
WORKDIR /tmp/
ADD conanfile.py .
RUN mkdir -p build_conan                                              \
    && cd /tmp/build_conan                                            \
    && conan install .. -s compiler.libcxx=libstdc++11 --build=missing

WORKDIR /
RUN mkdir -p /models/pose                                                                                                                                 
RUN mkdir -p /models/pose/coco                                                                                                                         
RUN mkdir -p /models/pose/mpi                                                                                                                          

WORKDIR /models/pose/coco                                                                                                                              
RUN wget -c http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel                                                
RUN wget -c https://raw.githubusercontent.com/CMU-Perceptual-Computing-Lab/openpose/v1.4.0/models/pose/coco/pose_deploy_linevec.prototxt              

WORKDIR /models/pose/mpi                                                                                                                               
RUN wget -c http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/mpi/pose_iter_160000.caffemodel                                                      
RUN wget -c https://raw.githubusercontent.com/CMU-Perceptual-Computing-Lab/openpose/v1.4.0/models/pose/mpi/pose_deploy_linevec.prototxt               
RUN wget -c https://raw.githubusercontent.com/CMU-Perceptual-Computing-Lab/openpose/v1.4.0/models/pose/mpi/pose_deploy_linevec_faster_4_stages.prototxt

WORKDIR /
RUN rm -rf /tmp/*